spring.datasource.url=jdbc:mysql://localhost:3306/suabase
spring.datasource.username=root
spring.datasource.password=Fatec123*
spring.jpa.hibernate.ddl-auto=update
spring.jpa
::contentReference[oaicite:0]{index=0}

